// ============================================================================
// GerReceipt.jsx
// ----------------------------------------------------------------------------
// Diagnostic Receipt — the structured-evidence output you take to a regulator,
// insurer, vendor, or class-action attorney when filing an AI-incident claim.
//
// Built per the NotebookLM deterministic redesign: 4 fixed sections, no AI,
// pure logic. Inputs: one or more GER codes (selected by the user from the
// lookup tool). Output: a printable / markdown-exportable document.
// ============================================================================

// Mintlify provides React hooks (useState/useMemo) globally — no import needed.
import gerData from "../data/ger.json";

const codes = gerData.codes;
const codeMap = new Map(codes.map((c) => [c.code, c]));

// ---------------------------------------------------------------------------
// Static per-code data the receipt needs.
// Eventually moves into the DB (ger_codes.evidence_checklist, ger_codes.regulatory_mappings)
// — but for v0.2 launch this is the hard-coded fallback so the receipt works
// even on codes that haven't had their per-code metadata authored yet.
//
// Defaults (used when a code has no specific entry) keep the receipt useful
// rather than blank.
// ---------------------------------------------------------------------------

const DEFAULT_EVIDENCE = [
  "The output / action / event itself (screenshot, document, log, transcript)",
  "Identifiers — transaction IDs, case numbers, model versions, timestamps",
  "Your inputs — what you said/asked/clicked that led to the failure",
  "System context — vendor name, product version, the surface (web / mobile / API)",
  "Vendor communications — your messages to them and their responses",
  "Vendor's stated policy at the time — screenshot the relevant policy pages",
  "Date and time of everything, including when you preserved each piece",
];

const EVIDENCE_PER_CODE = {
  "322": [
    "The synthetic output (image / audio / video / text)",
    "URL where it surfaced (social media post, ad, message)",
    "Date the output was first observed",
    "Any visible watermark or absence thereof",
    "Vendor's stated provenance policy at the time",
  ],
  "420": [
    "Vendor's published policy stating the prohibition",
    "Evidence the prohibited action was taken anyway",
    "Date the prohibition was published vs date the action occurred",
    "Any vendor acknowledgment of the policy-vs-production gap",
  ],
  "424": [
    "The denial / suspension / arrest notice",
    "Application materials (if applicable)",
    "Appeal communications and response timing",
    "Demographic data relevant to disparate-impact analysis",
    "Pattern data — news articles, ProPublica investigations, class actions",
  ],
  "428": [
    "The personalized output involving the named subject",
    "Evidence of who requested it (account, IP, identity)",
    "Whether consent of the subject was attested at any step",
    "Vendor's stated policy on third-party content generation",
  ],
  "432": [
    "Full chat transcript (request from vendor under data-subject access rights)",
    "Time stamps showing duration of conversations",
    "Vendor's stated mental-health safety policies",
    "Medical records / coroner findings (if applicable)",
    "Vendor's public statements about safety on this surface",
  ],
  "501": [
    "Evidence the detection fired (vendor logs if available)",
    "Evidence no escalation occurred (no report to authorities)",
    "Whether the vendor has any published escalation policy",
    "Statutory disclosure obligations that should have applied (24hr, 72hr, etc.)",
  ],
  "512": [
    "The fabricated content with the action directive",
    "Evidence the user did not introduce the fabricated premise",
    "Full conversation log showing how the premise was generated by the system",
    "Any real-world action taken on the directive",
  ],
};

const DEFAULT_REGULATORY = [
  "Vendor's customer support (cite the GER code)",
  "Vendor's legal / compliance contact if no resolution",
];

const REGULATORY_PER_CODE = {
  "322": [
    "Platform's content moderation team",
    "Law enforcement if fraud / NCII / electoral deepfake",
    "FTC for deceptive practices",
    "State AG for impersonation",
  ],
  "420": [
    "Vendor first, then FTC if marketed safeguards proved illusory",
    "State AGs investigating AI safety claims",
    "Class-action attorneys for systemic pattern",
  ],
  "424": [
    "Vendor's appeals process (file even if nominal — creates paper trail)",
    "HUD (housing), CFPB (lending), EEOC (employment), state ombudsperson (benefits)",
    "Class-action attorneys for systemic patterns",
    "AI Incident Database (incidentdatabase.ai)",
  ],
  "428": [
    "Platform content moderation (with explicit GER code citation)",
    "Law enforcement if subject is a minor or content is non-consensual sexual imagery",
    "NCMEC, IWF, or country-specific equivalents",
  ],
  "432": [
    "Vendor's safety team (with explicit GER code citation)",
    "Legal counsel specializing in product liability / AI harm",
    "State AG (multiple are actively investigating AI mental-health harm)",
    "FTC for unfair-and-deceptive-practices",
  ],
  "501": [
    "Vendor's safety team (with timing of when detection fired)",
    "Statutory regulator for jurisdiction (CA TFAIA, NY RAISE Act, OR SB 1546, EU AI Act)",
    "Local law enforcement (if imminent-harm signal)",
    "Class-action attorneys for systemic neglect",
  ],
  "512": [
    "Vendor incident reporting",
    "Law enforcement if real-world harm followed",
    "FTC for deceptive/unfair practices",
    "AI Incident Database for pattern documentation",
  ],
};

const evidenceFor    = (code) => EVIDENCE_PER_CODE[code]   ?? DEFAULT_EVIDENCE;
const regulatoryFor  = (code) => REGULATORY_PER_CODE[code] ?? DEFAULT_REGULATORY;

// ---------------------------------------------------------------------------
// Receipt-as-markdown export (the user's downloadable diagnostic document)
// ---------------------------------------------------------------------------
const buildMarkdown = (selectedCodes, context, distinctFromNotes) => {
  const lines = [];
  const today = new Date().toISOString().slice(0, 10);

  lines.push("# SVRNOS Diagnostic Receipt");
  lines.push("");
  lines.push(`**Generated:** ${today}`);
  lines.push("**Source:** SVRNOS Governance Error Register — https://docs.svrnos.com/ger");
  lines.push("");

  if (context?.trim()) {
    lines.push("## Case description");
    lines.push("");
    lines.push(context.trim());
    lines.push("");
  }

  // 1. Diagnosis
  lines.push("## 1. Diagnosis");
  lines.push("");
  selectedCodes.forEach((code, idx) => {
    const c = codeMap.get(code);
    if (!c) return;
    const roleLabel = idx === 0 ? "Primary" : (idx === 1 ? "Secondary" : "Contributing");
    lines.push(`### ${roleLabel} — GER-${c.code} ${c.name}`);
    lines.push("");
    lines.push(`*Tier: ${c.tier}${c.layer ? ` · Layer: ${c.layer}` : ""} · Status: ${c.type}*`);
    lines.push("");
    lines.push(c.definition);
    lines.push("");
    lines.push(`Source: https://docs.svrnos.com/ger/codes/${c.code}`);
    lines.push("");
  });

  // 2. Evidence checklist
  lines.push("## 2. Evidence to preserve");
  lines.push("");
  const allEvidence = new Set();
  selectedCodes.forEach((code) => evidenceFor(code).forEach((e) => allEvidence.add(e)));
  Array.from(allEvidence).forEach((e) => lines.push(`- [ ] ${e}`));
  lines.push("");

  // 3. Regulatory mapping / escalation
  lines.push("## 3. Where to escalate");
  lines.push("");
  const allReg = new Set();
  selectedCodes.forEach((code) => regulatoryFor(code).forEach((r) => allReg.add(r)));
  Array.from(allReg).forEach((r) => lines.push(`- ${r}`));
  lines.push("");

  // 4. Distinct-from justification (why these codes, not others)
  if (distinctFromNotes?.trim()) {
    lines.push("## 4. Why these codes (and not adjacent ones)");
    lines.push("");
    lines.push(distinctFromNotes.trim());
    lines.push("");
  } else {
    lines.push("## 4. Why these codes");
    lines.push("");
    selectedCodes.forEach((code) => {
      const c = codeMap.get(code);
      if (!c?.distinct_from?.length) return;
      lines.push(`**GER-${code} ${c.name}** is distinct from:`);
      c.distinct_from.forEach((d) => {
        lines.push(`- GER-${d.contrasted_with}: ${d.this_condition} → GER-${code}. ${d.other_condition} → GER-${d.contrasted_with}.`);
      });
      lines.push("");
    });
  }

  lines.push("---");
  lines.push("");
  lines.push("This receipt classifies a single incident against the SVRNOS Governance Error Register.");
  lines.push("It is generated by a deterministic filter (no AI), not a diagnostic LLM. The user selected the codes.");
  lines.push("Each code is open and citable under CC BY 4.0. The taxonomy is versioned; cite this receipt with the current GER version.");
  lines.push("");
  lines.push("If you intend to use this receipt in regulatory filing, litigation, or insurance claim — please notify SVRNOS at hello@svrnos.com so we can track adoption.");

  return lines.join("\n");
};

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------
export const GerReceipt = ({ defaultCode = "" }) => {
  const [selectedCodes, setSelectedCodes] = useState(defaultCode ? [defaultCode] : []);
  const [context, setContext] = useState("");
  const [distinctNotes, setDistinctNotes] = useState("");
  const [codeInput, setCodeInput] = useState("");

  const markdown = useMemo(
    () => buildMarkdown(selectedCodes, context, distinctNotes),
    [selectedCodes, context, distinctNotes]
  );

  const addCode = () => {
    const v = codeInput.trim();
    if (!v || !codeMap.has(v) || selectedCodes.includes(v)) return;
    setSelectedCodes([...selectedCodes, v]);
    setCodeInput("");
  };

  const removeCode = (code) => setSelectedCodes(selectedCodes.filter((c) => c !== code));

  const moveUp = (idx) => {
    if (idx === 0) return;
    const next = [...selectedCodes];
    [next[idx - 1], next[idx]] = [next[idx], next[idx - 1]];
    setSelectedCodes(next);
  };

  const download = () => {
    const blob = new Blob([markdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    const today = new Date().toISOString().slice(0, 10);
    a.href = url;
    a.download = `ger-receipt-${selectedCodes.join("-")}-${today}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const copyToClipboard = () => {
    navigator.clipboard?.writeText(markdown);
  };

  return (
    <div className="ger-receipt not-prose grid grid-cols-1 lg:grid-cols-2 gap-8">

      {/* INPUT side */}
      <div className="space-y-6">
        <h3 className="text-base font-mono uppercase tracking-wider text-neutral-600">Build your receipt</h3>

        {/* Code selection — primary, then secondary, then contributing */}
        <div>
          <label className="block text-xs font-mono uppercase tracking-wider text-neutral-600 mb-2">
            Codes (in role order)
          </label>
          <ol className="space-y-2 mb-3">
            {selectedCodes.map((code, idx) => {
              const c = codeMap.get(code);
              const roleLabel = idx === 0 ? "Primary" : (idx === 1 ? "Secondary" : "Contributing");
              return (
                <li key={code} className="flex items-center gap-2 border border-neutral-200 rounded p-2">
                  <span className="text-[10px] font-mono uppercase tracking-wider text-neutral-500 w-20">{roleLabel}</span>
                  <span className="font-mono text-sm text-green-900 font-semibold">GER-{code}</span>
                  <span className="text-sm flex-1">{c?.name ?? "(unknown)"}</span>
                  <button onClick={() => moveUp(idx)} disabled={idx === 0}
                    className="text-xs px-2 py-0.5 text-neutral-500 disabled:opacity-30 hover:text-neutral-900">↑</button>
                  <button onClick={() => removeCode(code)}
                    className="text-xs px-2 py-0.5 text-neutral-500 hover:text-red-700">×</button>
                </li>
              );
            })}
          </ol>
          <div className="flex gap-2">
            <input type="text" value={codeInput}
              onChange={(e) => setCodeInput(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && addCode()}
              placeholder="Add code (e.g. 501)"
              className="flex-1 px-3 py-2 border border-neutral-300 rounded text-sm" />
            <button onClick={addCode}
              className="px-4 py-2 bg-green-700 text-white text-sm rounded hover:bg-green-800">
              Add
            </button>
          </div>
        </div>

        {/* Context */}
        <div>
          <label className="block text-xs font-mono uppercase tracking-wider text-neutral-600 mb-2">
            Case description (optional)
          </label>
          <textarea value={context} onChange={(e) => setContext(e.target.value)}
            placeholder="Brief plain-language description of what happened. This appears at the top of the receipt."
            rows={4}
            className="w-full px-3 py-2 border border-neutral-300 rounded text-sm" />
        </div>

        {/* Distinct-from justification */}
        <div>
          <label className="block text-xs font-mono uppercase tracking-wider text-neutral-600 mb-2">
            Why these codes (optional)
          </label>
          <textarea value={distinctNotes} onChange={(e) => setDistinctNotes(e.target.value)}
            placeholder="Why these codes specifically, and not adjacent ones. If left blank, the receipt auto-fills with each code's structured distinct-from data."
            rows={3}
            className="w-full px-3 py-2 border border-neutral-300 rounded text-sm" />
        </div>

        {selectedCodes.length > 0 && (
          <div className="flex gap-3 pt-4 border-t border-neutral-200">
            <button onClick={download}
              className="px-4 py-2 bg-green-700 text-white text-sm rounded hover:bg-green-800">
              Download .md
            </button>
            <button onClick={copyToClipboard}
              className="px-4 py-2 border border-neutral-300 text-sm rounded hover:bg-neutral-50">
              Copy to clipboard
            </button>
          </div>
        )}
      </div>

      {/* PREVIEW side */}
      <div>
        <h3 className="text-base font-mono uppercase tracking-wider text-neutral-600 mb-3">Preview</h3>
        {selectedCodes.length === 0 ? (
          <div className="border border-neutral-200 rounded p-8 text-center text-neutral-500 text-sm">
            <p className="mb-2">Add at least one GER code to generate a receipt.</p>
            <p className="text-xs">
              Don't know which code? Use the <a href="/ger/find" className="underline">lookup tool</a> first.
            </p>
          </div>
        ) : (
          <pre className="border border-neutral-200 rounded p-4 bg-neutral-50 text-xs overflow-auto max-h-[600px] whitespace-pre-wrap font-mono">{markdown}</pre>
        )}
      </div>
    </div>
  );
};
